name: Build Wheels

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
        exclude:
          - os: macos-latest
            python-version: "3.7"
          - os: macos-latest
            python-version: "3.1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.14.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Test with pytest
        run: |
          python -m unittest

      - name: Build wheels
        env:
          CIBW_BUILD: cp3?-*  # Builds for Python 3.x (excluding 3.6)
          CIBW_SKIP: cp36-*  # Skips Python 3.6
          CIBW_TEST_REQUIRES: pytest  # Replace with actual test dependencies
          CIBW_TEST_COMMAND: "pytest {project}/tests"  # Replace with your test command
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels
          path: wheelhouse/*.whl
