name: Build Wheels

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_wheels:
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      matrix:
        buildplat: 
        - [ubuntu-20.04, manylinux_x86_64]
        - [ubuntu-20.04, manylinux_aarch64]
        - [ubuntu-20.04, manylinux_i686]
        - [ubuntu-20.04, musllinux_x86_64]
        - [ubuntu-20.04, musllinux_aarch64]
        - [macos-11, macosx_*]
        - [windows-2019, win_amd64]
        - [windows-2019, win32]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Test with pytest
        run: |
          python -m unittest

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          # TODO: Build Cython with the compile-all flag?
          # Unfortunately, there is no way to modify cibuildwheel's build command
          # so there is no way to pass this in directly.
          # This would require modifying cython's setup.py to look for these flags
          # in env vars.
          CIBW_BUILD: "cp3?-*"
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ENVIRONMENT: CFLAGS='-O3 -g0 -mtune=generic -pipe -fPIC' LDFLAGS='-fPIC'
          # TODO: Cython tests take a long time to complete
          # consider running a subset in the future?
          #CIBW_TEST_COMMAND: python {project}/runtests.py -vv --no-refnanny

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels
          path: wheelhouse/*.whl
