name: Build Wheels

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Test with pytest
        run: |
          python -m unittest

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels
          path: dist/*.whl
  upload_to_pypi:
    name: Upload release to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: built-wheels
          path: dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
